"""
Auto-generate project_layout.md from the real filesystem tree.

Usage:
    uv run python scripts/gen_project_layout.py
    uv run python scripts/gen_project_layout.py --out my_layout.md

Excludes gitignored / build / cache directories automatically.
Existing description annotations in project_layout.md are NOT preserved —
this script produces a clean structural snapshot every time.
"""

from __future__ import annotations

import argparse
from pathlib import Path

# Directories that are never interesting to agents
SKIP_DIRS = {
    ".git",
    ".venv",
    "node_modules",
    "__pycache__",
    ".pytest_cache",
    ".ruff_cache",
    ".uv-cache",
    ".uv_cache",
    ".pixi",
    "dist",
    "build",
    ".vite",
    "out",
    "tmp",
    "logs",
    "playwright-report",
    "test-results",
    ".mypy_cache",
    ".pytype",
    "cython_debug",
    ".eggs",
    "htmlcov",
    ".tox",
    ".nox",
    ".hypothesis",
    ".abstra",
    "__marimo__",
    "marimo/_static",
    "marimo/_lsp",
}

# Files to always skip
SKIP_FILES = {
    ".DS_Store",
    "*.pyc",
    "*.pyo",
    "*.pyd",
    "package-lock.json",
}

# Short per-path descriptions shown inline.
# Keys are relative paths (POSIX) from the project root.
# Edit this dict to add annotations — they survive re-runs.
DESCRIPTIONS: dict[str, str] = {
    # Root
    "src": "Python package (CLI + pipeline)",
    "app": "Web application (FastAPI backend + React frontend)",
    "app/backend": "FastAPI backend",
    "app/backend/api": "Route handlers",
    "app/backend/services": "Business logic",
    "app/backend/middleware": "HTTP middleware",
    "app/backend/tests": "Backend unit tests",
    "app/frontend": "React + Vite frontend",
    "app/frontend/src": "Frontend source",
    "app/frontend/src/pages": "Page components",
    "app/frontend/src/components": "Reusable UI components",
    "app/frontend/src/hooks": "Custom React hooks",
    "app/frontend/src/api": "Typed API client functions",
    "app/frontend/src/stores": "Zustand state stores",
    "app/e2e": "Playwright end-to-end tests",
    "data": "Your CV data (edit these) — gitignored",
    "jobs": "Job descriptions for targeted builds — gitignored",
    "config": "LLM config (llm.env) — gitignored",
    "docs": "Generated documentation and indexes",
    "scripts": "Dev/maintenance scripts",
    "templates": "PDF layout templates",
    "prompts": "AI prompts for bullet rewriting",
    "examples": "Safe bundled working examples",
    "tests": "CLI unit and integration tests",
    # Key files
    "src/cv_compiler/cli.py": "CLI entry point",
    "src/cv_compiler/pipeline.py": "Build pipeline",
    "app/backend/main.py": "FastAPI app factory + lifespan",
    "app/frontend/src/App.tsx": "Root component + routing",
    "start.sh": "Launch backend + frontend (use: bash start.sh [--force])",
    "Makefile": "make start / make test / make metadata / make update",
    "CLAUDE.md": "Project guide for Claude Code",
    "project_layout.md": "This file — auto-generated by scripts/gen_project_layout.py",
    "docs/code_metadata.md": "Auto-generated: lines, complexity, local deps per file",
    "docs/PROJECT_INDEX.md": "Auto-generated: Python import graph",
}


def _should_skip_dir(name: str) -> bool:
    return name in SKIP_DIRS or name.startswith(".")


def _should_skip_file(name: str) -> bool:
    for pat in SKIP_FILES:
        if pat.startswith("*"):
            if name.endswith(pat[1:]):
                return True
        elif name == pat:
            return True
    return False


def _build_tree(root: Path) -> list[str]:
    lines: list[str] = []
    _walk(root, root, "", lines, is_last=True)
    return lines


def _walk(
    root: Path,
    path: Path,
    prefix: str,
    lines: list[str],
    is_last: bool,
) -> None:
    rel = path.relative_to(root).as_posix() if path != root else ""
    name = path.name if path != root else root.name
    connector = "" if path == root else ("└── " if is_last else "├── ")
    desc = DESCRIPTIONS.get(rel, "")
    desc_str = f"  # {desc}" if desc else ""

    if path == root:
        lines.append(f"{name}/{desc_str}")
    else:
        lines.append(f"{prefix}{connector}{name}{'/' if path.is_dir() else ''}{desc_str}")

    if not path.is_dir():
        return

    child_prefix = prefix + ("    " if is_last else "│   ") if path != root else ""

    try:
        children = sorted(
            path.iterdir(),
            key=lambda p: (p.is_file(), p.name.lower()),
        )
    except PermissionError:
        return

    visible = [
        c for c in children
        if not (c.is_dir() and _should_skip_dir(c.name))
        and not (c.is_file() and _should_skip_file(c.name))
    ]

    for i, child in enumerate(visible):
        _walk(root, child, child_prefix, lines, is_last=(i == len(visible) - 1))


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate project_layout.md")
    parser.add_argument("--out", type=Path, default=Path("project_layout.md"))
    args = parser.parse_args(argv)

    root = Path.cwd()
    tree_lines = _build_tree(root)

    content = "\n".join([
        "# Project Layout",
        "",
        "> Auto-generated by `scripts/gen_project_layout.py` — do not edit manually.",
        "> Re-run with: `uv run python scripts/gen_project_layout.py`",
        "",
        "```",
        *tree_lines,
        "```",
        "",
    ])

    out: Path = args.out
    out.write_text(content, encoding="utf-8")
    print(f"[✓] {out} updated ({len(tree_lines)} entries)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
